### ISSUE TITLE
Incorrect convertion of object in SQLI honeypots

### ISSUE THREAD

**Issue by NotReeceHarris** [NotReeceHarris/honeypots.js#2]
```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at module.exports (Z:\test\web-app\node_modules\honeypots.js\src\honeypots\sqli_injection.js:11:38)
    at Z:\test\web-app\node_modules\honeypots.js\src\index.js:59:13
    at Layer.handle [as handle_request] (Z:\test\web-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (Z:\test\web-app\node_modules\express\lib\router\index.js:328:13)
    at Z:\test\web-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (Z:\test\web-app\node_modules\express\lib\router\index.js:346:12)
    at next (Z:\test\web-app\node_modules\express\lib\router\index.js:280:10)
    at Z:\test\web-app\index.js:90:3
    at Layer.handle [as handle_request] (Z:\test\web-app\node_modules\express\lib\router\layer.js:95:5)
```

**Comment by NotReeceHarris** [comment]
Fixed for SQLI and XSS in latest commit
